language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist
    - travis_retry composer dump-autoload -o

script:
    - composer run-script phpstan
    - composer run-script tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
    directories:
        - $HOME/.composer/cache